@baseURL = http://localhost:3333 
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseURL}}/accounts
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Joao da Silva",
    "email": "joaosilva3@ecoeletrica.com.br",
    "password": "123456",
    "cpf":"12345678912",
    "type": "Administrator",
    "baseId": "352275c2-c358-4367-8f97-b21de8a170da"
}

###

# @name authenticate
POST {{baseURL}}/sessions
Content-Type: application/json

{
    "email": "joaosilva@ecoeletrica.com.br",
    "password": "123456" 
}

###

# @name create_material
POST {{baseURL}}/materials
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "code": 123456,
    "description": "item poste 123",
    "type": "FERRAGEM",
    "unit": "CDA",
    "contractId": "352275c2-c358-4367-8f97-b21de8a170da"
}

###

# @name fetch_materials
GET {{baseURL}}/materials?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "type": "FERRAGEM",
    "contractId": "352275c2-c358-4367-8f97-b21de8a170da"
}