@baseURL = http://localhost:3333 
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseURL}}/accounts
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Max",
    "email": "max@ecoeletrica.com.br",
    "password": "123456",
    "cpf":"12345678912",
    "type": "Administrator",
    "baseId": "35cf180f-140b-4aa6-855f-7e2f1117a0e8"
}

###

# @name authenticate
POST {{baseURL}}/sessions
Content-Type: application/json

{
    "email": "rodrigo1@ecoeletrica.com.br",
    "password": "123456" 
}

###

# @name create_material
POST {{baseURL}}/materials
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "code": 1123456,
    "description": "item poste 123",
    "type": "FERRAGEM",
    "unit": "CDA",
    "contractId": "352275c2-c358-4367-8f97-b21de8a170da"
}

###

# @name fetch_materials
GET {{baseURL}}/materials?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "type": "FERRAGEM",
    "contractId": "352275c2-c358-4367-8f97-b21de8a170da"
}

###

# @name get_user_by_id
GET {{baseURL}}/accounts/7ddd9b43-93f2-4474-9a8a-847bce3c1e6e
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name edit_account
PUT {{baseURL}}/accounts/eeeb2452-3010-4d98-bb20-cf663e5eab49
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "password": "123456",
    "type": "Almox",
    "baseId": "352275c2-c358-4367-8f97-b21de8a170da"
}

###

# @name delete_user_by_id
DELETE  {{baseURL}}/accounts/2d8c64e4-0ae3-448e-8fa4-eb4edaaaf963
Content-Type: application/json
Authorization: Bearer {{authToken}}


###

# @name fetch_account
GET {{baseURL}}/accounts?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "baseId": "352275c2-c358-4367-8f97-b21de8a170da"
}


###

# @name register_contract
POST {{baseURL}}/contracts
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "contractName": "Oeste Pernambuco"
}


###

# @name fetch_contracts
GET {{baseURL}}/contracts?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}


###

# @name register_base
POST {{baseURL}}/bases
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "baseName": "Petrolina",
    "contractId": "a100663c-5a6d-4198-ad7b-1062afa0c4f4"
}


###

# @name fetch_bases
GET {{baseURL}}/bases?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}


###

# @name identifier_attribution
POST {{baseURL}}/physical-documents
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "projectId": "352275c2-c358-4367-8f97-b21de8a170da",
    "identifier": 3
}


###

# @name fetch_physical_documents
GET {{baseURL}}/physical-documents?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "projectId": "e816f105-e022-4560-b32c-d2af40c18351"
}


###

# @name uniteze_physical_documents
PUT {{baseURL}}/physical-documents/fc13dc69-7493-4644-9667-576cfaf85735
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "unitized": true
}


###

# @name delete_physical_document
DELETE  {{baseURL}}/physical-documents/88b6a558-046d-47bf-be45-11fccec6d328
Content-Type: application/json
Authorization: Bearer {{authToken}}


###

# @name transfer_material
POST  {{baseURL}}/movimentation
Content-Type: application/json
Authorization: Bearer {{authToken}}

[
    {
        "materialId": "88b6a558-046d-47bf-be45-11fccec6d328",
        "projectId": "88b6a558-046d-47bf-be45-11fccec6d328",
        "observation": "nao sei das quantas",
        "baseId": "88b6a558-046d-47bf-be45-11fccec6d328",
        "value": 5
    },
    {
        "materialId": "88b6a558-046d-47bf-be45-11fccec6d328",
        "projectId": "88b6a558-046d-47bf-be45-11fccec6d328",
        "observation": "nao sei das quantas",
        "baseId": "88b6a558-046d-47bf-be45-11fccec6d328",
        "value": 2
    },
    {
        "materialId": "88b6a558-046d-47bf-be45-11fccec6d328",
        "projectId": "88b6a558-046d-47bf-be45-11fccec6d328",
        "observation": "nao sei das quantas",
        "baseId": "88b6a558-046d-47bf-be45-11fccec6d328",
        "value": -1
    }
]


###

# @name register_project
POST  {{baseURL}}/projects
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "project_number": "B-12345678",
    "description": "MP-NUM-SEI-DAS-QUANTAS",
    "type": "obra",
    "baseId": "88b6a558-046d-47bf-be45-11fccec6d328",
    "city": "Ituí"
}


###

# @name transfer_movimentation_between_projects
POST  {{baseURL}}/transfer-movimentation
Content-Type: application/json
Authorization: Bearer {{authToken}}

[
    {
        "materialId": "88b6a558-046d-47bf-be45-11fccec6d328",
        "projectIdOut": "88b6a558-046d-47bf-be45-11fccec6d328",
        "projectIdIn": "30d2f9c4-decc-418a-bc5d-0fb16db7af57",
        "observation": "Num sei das quantas",
        "baseId": "88b6a558-046d-47bf-be45-11fccec6d328",
        "value": 5
    }
]

###

# @name fetch_movimentations
GET {{baseURL}}/movimentations?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "baseId": "88b6a558-046d-47bf-be45-11fccec6d328"
}